name: Test
permissions: read-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14, ubuntu-24.04-arm]
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          ./.github/install_clang_version.sh 19

      - name: "Run analysis tests"
        run: |
          bazelisk test //heir/...

      - name: "Run OpenFHE integration tests"
        env:
          OPENFHE_FLAGS: ${{ runner.os == 'macOS' && '--@openfhe//:enable_openmp=False' || '' }}
        run: |
          cd examples/openfhe
          bazelisk build //... $OPENFHE_FLAGS

          EXPECTED_FILE="bazel-bin/hello_world_lib.inc.cc"
          if [[ ! -f "$EXPECTED_FILE" ]]; then
            echo "Error: File '$EXPECTED_FILE' not found." >&2
            exit 1
          fi

          echo "File '$EXPECTED_FILE' successfully generated."
          bazelisk test //... $OPENFHE_FLAGS

      - name: "Run Lattigo integration tests"
        run: |
          cd examples/lattigo
          bazelisk build //...

          EXPECTED_FILE="bazel-bin/helloworld_lib.go"
          if [[ ! -f "$EXPECTED_FILE" ]]; then
            echo "Error: File '$EXPECTED_FILE' not found." >&2
            exit 1
          fi

          echo "File '$EXPECTED_FILE' successfully generated."
          bazelisk test //...
